baseURL = 'https://just-plain-notes.blog/'
languageCode = 'ja'
title = 'Tech Blog'
theme = 'JustPlain'
defaultContentLanguage = "ja"
defaultContentLanguageInSubdir = false

[languages]
  [languages.ja]
    weight = 1
    languageName = '日本語'
    contentDir = 'content/ja'
    title = "Just Plain Notes"

  [languages.en]
    weight = 2
    languageName = 'English'
    contentDir = 'content/en'
    title = "Just Plain Notes"

[pagination]
pagerSize = 5
enableEmoji = true

[params]
description = "個人的に気になったことのメモなど"
author = 'kengo'
googleAnalytics = "G-GW5ZZD3TH2"
showToc = true
showCodeCopyButtons = true
showReadingTime = true
showShareButtons = true
showPostNavLinks = true
showBreadCrumbs = true
showWordCount = true
showFullTextinRSS = true
ShowPageNums = true
defaultTheme = 'auto'

[params.homeInfoParams]
Title = 'Tech Blog'
Content = '技術情報とプログラミング'

[menu]
  [[menu.main]]
    identifier = 'home'
    name = 'Home'
    url = '/'
    weight = 10

  [[menu.main]]
    identifier = 'posts'
    name = 'Posts'
    url = '/posts/'
    weight = 20

  [[menu.main]]
    identifier = 'tags'
    name = 'Tags'
    url = '/tags/'
    weight = 30

  [[menu.main]]
    identifier = 'archives'
    name = 'Archives'
    url = '/archives/'
    weight = 40

  [[menu.main]]
    identifier = 'contact'
    name = 'Contact'
    url = '/contact/'
    weight = 50

[taxonomies]
tag = 'tags'

[frontmatter]
date = ["date", ":fileModTime"]

[languages.en.params]
  description = "Personal notes on what sparked my curiosity"

[markup]
  [markup.highlight]
    noClasses = false
    style = "github"
    lineNos = false

[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[outputs]
home = ["HTML", "RSS", "JSON", "CALENDAR"]

[outputFormats]
  [outputFormats.CALENDAR]
    mediaType = "application/json"
    baseName = "calendar-data"
    isPlainText = true

[params.fuseOpts]
limit = 10
